import type { HabitId, MealGroup, SportPreference } from './types'

type RawOption = [id: string, name: string, calories: number, protein: number, carbs: number, recipeUrl?: string]

const englishMealNames: Record<string, string> = {
  'cottage-pancake': 'Cottage cheese pancakes',
  'labneh-toast': 'Whole-grain toast with labneh',
  takwira: 'Ground beef pita',
  eggs: 'Eggs with whole-grain bread',
  foul: 'Fava beans with pita and vegetables',
  'turkey-toast': 'Smoked turkey and cheese toast',
  'cottage-honey': 'Cottage cheese with honey and strawberries',
  'tiktok-pancake': 'High-protein pancakes',
  'tiktok-omelette': 'Healthy omelette',
  qatayef: 'Diet qatayef',
  mafrookeh: 'Healthy mafroukeh',
  'diet-soup': 'High-protein soup',
  'rice-halawa': 'Rice pudding',
  'healthy-dessert': 'Protein dessert',
  'pistachio-cake': 'Pistachio cake',
  'protein-bar': 'Homemade protein bar',
  lupin: 'Boiled lupini beans',
  'french-toast': 'French toast',
  'baked-potato': 'Baked potato',
  'white-cheese': 'White cheese with whole-grain toast',
  falafel: 'Baked falafel',
  'milk-oats': 'Skim milk with oats',
  edamame: 'Boiled edamame',
  'protein-yogurt': 'Greek yogurt with berries',
  'healthy-cookies': 'Healthy cookies',
  'cake-pieces': 'Two pieces of cake',
  pudding: 'Diet pudding',
  'healthy-burger': 'Healthy burger',
  'meat-rice': 'Beef with rice',
  'baked-meat': 'Oven-baked beef with pita',
  'red-pasta': 'Beef pasta with tomato sauce',
  'tray-chicken': 'Oven-baked chicken',
  'healthy-crisp': 'Healthy crispy chicken',
  'healthy-pasta': 'Healthy pasta',
  'chicken-sandwich': 'Chicken sandwich',
  'steak-potato': 'Steak or kofta with baked potato',
  fajita: 'Chicken fajita with mozzarella and pita',
  'tannour-bulgur': 'Chicken, bulgur and whole-grain pita',
  'chicken-potato': 'Chicken with baked potato',
  'chicken-rice': 'Chicken with rice',
  'chicken-breast-sandwich': 'Chicken breast sandwich',
  'healthy-cheesecake': 'Healthy cheesecake',
  'tuna-salad': 'Tuna and sweetcorn salad',
  'healthy-lasagna': 'Healthy lasagna',
  escalope: 'Chicken escalope',
  'sausage-pizza': 'Sausage pizza',
  'rice-chicken-light': 'Rice and chicken',
  'healthy-crepe': 'Diet chicken crêpe',
  'healthy-nuggets': 'Healthy chicken nuggets',
  'tiktok-pizza': 'Homemade diet pizza',
  'grape-leaves': 'Stuffed grape leaves',
  'kibbeh-tray': 'Baked kibbeh',
  'stuffed-zucchini': 'Stuffed zucchini',
  'tuna-pasta': 'Tuna pasta salad',
  'grilled-fish': 'Grilled fish with rice',
  'shrimp-rice': 'Shrimp with rice',
  'beans-rice': 'Vegetable stew with beef and rice',
  mujaddara: 'Mujaddara with yogurt',
  molokhia: 'Molokhia with chicken and rice',
  sushi: 'Ten pieces of sushi',
  'chicken-balls': 'Chicken balls',
}

const palettes = {
  breakfast: ['#f2c879', '🥞'],
  snack: ['#b89acb', '🥣'],
  lunch: ['#d28d5d', '🍗'],
  dinner: ['#7da28c', '🍽️'],
} as const

function options(group: keyof typeof palettes, rows: RawOption[]) {
  const [color, glyph] = palettes[group]
  return rows.map(([id, name, calories, protein, carbs, recipeUrl]) => ({
    id,
    name,
    nameEn: englishMealNames[id] ?? name,
    description: 'حصة محسوبة من الخطة الأصلية',
    descriptionEn: 'Portion calculated from the original plan',
    calories,
    protein,
    carbs,
    fat: Math.max(2, Math.round((calories - protein * 4 - carbs * 4) / 9)),
    color,
    glyph,
    imageUrl: `/meal-images/items/${id}.webp`,
    recipeUrl,
  }))
}

export const mealGroups: MealGroup[] = [
  {
    id: 'breakfast',
    title: 'الفطور',
    titleEn: 'Breakfast',
    subtitle: 'بداية مشبعة ليوم متوازن',
    subtitleEn: 'A satisfying start to a balanced day',
    time: '٨:٣٠ ص',
    timeEn: '8:30 AM',
    options: options('breakfast', [
      ['cottage-pancake', 'بانكيك قريشة', 350, 28, 33, 'https://www.instagram.com/reel/CytSYzCqTdE/?igsh=aHdka3ZxMmt1b2Z2'],
      ['labneh-toast', '٢ توست أو ربطة خبز (تنور/أسمر/قمحة كاملة) + ١٥٠غ لبنة', 290, 19, 40],
      ['takwira', 'تقويرة لحمة مدقوقة', 420, 33, 30, 'https://www.instagram.com/reel/Cy823GvIuvZ/?igsh=cXFlbGNhNHhubDZi'],
      ['eggs', 'بيض مسلوق أو مقلي بمسحة زيت زيتون + رغيف خبز أسمر/شوفان (أو ٢ توست) + حبة بندورة', 360, 30, 26],
      ['foul', 'علبة فول مدمس ٤٠٠غ + رغيف تنور مع جميع الخضار', 400, 25, 33],
      ['turkey-toast', '١٠٠غ حبش مدخن + ٢ توست (تنور/أسمر/قمحة كاملة) + حبتان قشقوان', 360, 28, 26],
      ['cottage-honey', '٢٥٠غ قريشة + ملعقة كبيرة عسل وفريز', 320, 20, 25],
      ['tiktok-pancake', 'بانكيك تيك توك', 325, 17, 50, 'https://www.instagram.com/reel/Cr1BAHpRtk5/?igsh=MXR6Z2R6NTFrdnF0Zg=='],
      ['tiktok-omelette', 'عجة التيك توك', 350, 20, 20, 'https://www.instagram.com/reel/CsHCX3XMCyi/?igsh=anBneWlscWh0ZDBr'],
    ]),
  },
  {
    id: 'snack',
    title: 'وجبة خفيفة',
    titleEn: 'Snack',
    subtitle: 'طاقة خفيفة بين الوجبات',
    subtitleEn: 'A light boost between meals',
    time: '١١:٣٠ ص',
    timeEn: '11:30 AM',
    options: options('snack', [
      ['qatayef', 'قطايف للدايت', 350, 28, 17, 'https://www.instagram.com/reel/DHJna0wCRDq/?igsh=MXJiYW5lNTIwMzlldQ=='],
      ['mafrookeh', 'مفروكة', 370, 18, 35, 'https://www.instagram.com/reel/DHHHJc5CaJa/?igsh=MXRmYW9hb2YzNzA4eg=='],
      ['diet-soup', 'شوربة دايت', 320, 40, 50, 'https://www.instagram.com/reel/C2pvHsHilqt/?igsh=MTJpbWliNHpxN3hneg=='],
      ['rice-halawa', 'حلاوة الرز', 280, 12, 25, 'https://www.instagram.com/reel/C1XXTcRCsRd/?igsh=OTNncDE3aWxsYzVj'],
      ['healthy-dessert', 'تحلية للدايت', 160, 25, 6, 'https://www.instagram.com/reel/C0j2-8XCoPA/?igsh=dzlzaWpwMzBrOTJ4'],
      ['pistachio-cake', 'كيك الفستق تيك توك', 300, 17, 27, 'https://www.instagram.com/reel/CjYU-yYDI5N/?igsh=MWo2NmtibXJtOTNmcg=='],
      ['protein-bar', 'بروتين بار منتن', 350, 20, 30, 'https://www.instagram.com/reel/Cs37wOWslXr/?igsh=dXM1bDdlNjB2bGZ2'],
      ['lupin', '٢٥٠غ ترمس', 280, 25, 30],
      ['french-toast', 'توست بالطريقة الفرنسية', 340, 22, 35, 'https://www.instagram.com/reel/Csl6YLzsqa4/?igsh=cHF4MHdzMXV5dmJw'],
      ['baked-potato', 'بطاطا مشوية', 410, 30, 18, 'https://www.instagram.com/reel/CyQ_zZiIzfr/?igsh=MXViODJ6Z2wwYWoyNw=='],
      ['white-cheese', '١٠٠غ جبنة بيضاء + ٢ توست (تنور/أسمر/قمحة كاملة)', 370, 42, 30],
      ['falafel', 'فلافل صحية', 320, 12, 40, 'https://www.instagram.com/reel/Cu91Z-pgxuu/?igsh=MW93c2U2ODU3NHdjeA=='],
      ['milk-oats', '٤٠غ حليب بودرة خالي الدسم + ٢٥٠غ شوفان خالي الدسم', 280, 15, 40],
      ['edamame', '٤٠٠غ إدامامي مسلوق / لين بلدي', 350, 22, 40],
      ['protein-yogurt', '٤٠٠غ زبادي يوناني + توت (إضافة حسب الرغبة)', 300, 18, 15],
      ['healthy-cookies', 'كوكيز صحية', 300, 18, 30],
      ['cake-pieces', 'قطعتين كيك', 350, 20, 35],
      ['pudding', 'مهلبية دايت (وجبة من الصينية ٣٠٪)', 390, 30, 45],
    ]),
  },
  {
    id: 'lunch',
    title: 'الغداء',
    titleEn: 'Lunch',
    subtitle: 'الوجبة الرئيسية لليوم',
    subtitleEn: 'Your main meal of the day',
    time: '٣:٠٠ م',
    timeEn: '3:00 PM',
    options: options('lunch', [
      ['healthy-burger', 'برغر صحي', 370, 28, 25, 'https://www.instagram.com/reel/CzHJTOiou-K/?igsh=cXNyaXl6am91aWxk'],
      ['meat-rice', '٢٠٠غ لحمة + ١٠٠غ رز', 530, 57, 30],
      ['baked-meat', 'لحمة مسلية بالفرن ٢٠٠غ + رغيف تنور', 520, 42, 48],
      ['red-pasta', 'معكرونة بالصوص الأحمر ١٠٠غ + ٢٠٠غ لحمة', 520, 58, 39],
      ['tray-chicken', 'دجاج بالصينية', 450, 46, 30, 'https://www.instagram.com/reel/CxGSDChLZ-5/?igsh=YTh4dmJkdHVld3I3'],
      ['healthy-crisp', 'كرسب صحي', 400, 50, 8, 'https://www.instagram.com/reel/Cw0RqXCAgsB/?igsh=eGF6enJreXI1NTJ4'],
      ['healthy-pasta', 'معكرونة صحية', 500, 30, 50, 'https://www.instagram.com/reel/CvaIcKWAFQK/?igsh=MTc3aWxnNTZlOWg0ZA=='],
      ['chicken-sandwich', 'ساندويش دجاج', 460, 60, 30, 'https://www.instagram.com/reel/CwiNZ8QxM6v/?igsh=MXF1aHgydzdkYmdlMA=='],
      ['steak-potato', 'لحمة على أنواعها ٢٠٠غ (كفتة/ستيك) + بطاطا مشوية ١٢٥غ', 460, 30, 37],
      ['fajita', 'دجاج فاهيتا ٢٠٠غ + ٣٠غ موزاريلا + رغيف تنور', 550, 47, 25],
      ['tannour-bulgur', 'رغيف تنور + ١٠٠غ برغل + ١٠٠غ لين + ٢٠٠غ دجاج', 570, 58, 52],
      ['chicken-potato', '٢٠٠غ دجاج + بطاطا مشوية أو مسلوقة ١٢٥غ (مبهّرة)', 490, 53, 27, 'https://www.instagram.com/reel/C9SgCyiixes/?igsh=MTF4ZXQwZm9uNWpqeA=='],
      ['chicken-rice', '٢٠٠غ دجاج + ١٠٠غ رز', 510, 64, 25, 'https://www.instagram.com/reel/C9SgCyiixes/?igsh=MTF4ZXQwZm9uNWpqeA=='],
      ['chicken-breast-sandwich', 'ساندويش صدور دجاج + رغيف ٢٥٠ + خردل أو مايونيز لايت + خضار', 420, 57, 30],
      ['healthy-cheesecake', 'تشيز كيك صحي', 480, 40, 38, 'https://www.instagram.com/reel/Crv2Mbtsle9/?igsh=MW5nZjFnb3QzenhmcQ=='],
      ['tuna-salad', 'سلطة مع علبة تونا بدون زيت + ١٧٠غ ذرة حلوة', 300, 39, 25],
      ['healthy-lasagna', 'قطعتين لازانيا صحية', 500, 45, 24, 'https://www.instagram.com/reel/CqnPtj-g66s/?igsh=MWJ4aTRvY2NvcTEwcg=='],
    ]),
  },
  {
    id: 'dinner',
    title: 'العشاء',
    titleEn: 'Dinner',
    subtitle: 'نهاية خفيفة ومشبعة',
    subtitleEn: 'A light and satisfying finish',
    time: '٧:٣٠ م',
    timeEn: '7:30 PM',
    options: options('dinner', [
      ['escalope', 'اسكالوب', 500, 38, 33, 'https://www.instagram.com/reel/C8uX9Y2CRWo/?igsh=MW9xMXhhaTFhZXRpOQ=='],
      ['sausage-pizza', '٦ قطع بيتزا سجق', 450, 40, 30, 'https://www.instagram.com/reel/C7KDP-uCA8S/?igsh=MXZpaGo5eTkyeGtlMA%3D%3D'],
      ['rice-chicken-light', 'رز ودجاج', 400, 57, 30, 'https://www.instagram.com/reel/C3Ip5bFCRar/?igsh=bXN3ZnpiemI3cm8z'],
      ['healthy-crepe', 'كريب دايت', 420, 51, 30, 'https://www.instagram.com/reel/C2K2rs-iF5U/?igsh=MW1pNTQxdnBiYjBncw=='],
      ['healthy-nuggets', '١٠ حبات ناجتس (nuggets) صحية', 400, 28, 35, 'https://www.instagram.com/reel/CqTRXKjJWZ4/?igsh=dDhhdXRkbXFmOXZ1'],
      ['tiktok-pizza', 'نص بيتزا تيك توك', 470, 21, 50, 'https://www.instagram.com/reel/CpniGIpjFW7/?igsh=aWoyb3Z2cDBuZTRw'],
      ['grape-leaves', '٤٠٠غ ورق عنب', 450, 54, 35],
      ['kibbeh-tray', '٣٥٠غ كبة بالصينية + ١٠٠غ لين', 590, 36, 55],
      ['stuffed-zucchini', '٤٠٠غ كوسا محشي', 500, 56, 40],
      ['tuna-pasta', 'سلطة مع علبة تونا بدون زيت + ١٠٠غ معكرونة + ملعقة مايونيز لايت', 350, 32, 33],
      ['grilled-fish', 'أسماك مشوية + ٢٠٠غ رز', 480, 38, 48],
      ['shrimp-rice', '٢٠٠غ قريدس + ١٠٠غ رز', 330, 48, 30],
      ['beans-rice', 'فاصوليا/بازيلاء/لوبيا/بامية ٣٥٠غ (لحمة رأس عصفور) + ١٠٠غ رز', 430, 22, 45],
      ['mujaddara', 'مجدرة على أنواعها ٣٥٠غ + ١٠٠غ لين', 500, 18, 72],
      ['molokhia', 'ملوخية ٢٠٠غ + ١٠٠غ رز + ٢٠٠غ دجاج', 560, 60, 38],
      ['sushi', '١٠ حبات سوشي', 380, 12, 60],
      ['chicken-balls', '٤ حبات من كريات الدجاج', 280, 18, 22, 'https://www.instagram.com/reel/CrjApv7sIhN/?igsh=MTFuemI4cmZ0cHlwMA=='],
    ]),
  },
]

export const fruits = [
  { id: 'greengage', name: 'جانارك', nameEn: 'Greengage', amount: '١٥٠غ', amountEn: '150 g', calories: 115, glyph: '🟢' },
  { id: 'banana', name: 'موز', nameEn: 'Banana', amount: '١٠٠غ', amountEn: '100 g', calories: 115, glyph: '🍌' },
  { id: 'mango', name: 'مانجا', nameEn: 'Mango', amount: '١٥٠غ', amountEn: '150 g', calories: 115, glyph: '🥭' },
  { id: 'apple', name: 'تفاح', nameEn: 'Apple', amount: '٢٠٠غ', amountEn: '200 g', calories: 115, glyph: '🍎' },
  { id: 'papaya', name: 'بابايا', nameEn: 'Papaya', amount: '١٠٠غ', amountEn: '100 g', calories: 115, glyph: '🧡' },
  { id: 'pineapple', name: 'أناناس', nameEn: 'Pineapple', amount: '٢٠٠غ', amountEn: '200 g', calories: 115, glyph: '🍍' },
  { id: 'loquat', name: 'أكي دنيا', nameEn: 'Loquat', amount: '١٥٠غ', amountEn: '150 g', calories: 115, glyph: '🟠' },
  { id: 'peach', name: 'دراق', nameEn: 'Peach', amount: '٢٠٠غ', amountEn: '200 g', calories: 115, glyph: '🍑' },
  { id: 'plum', name: 'خوخ', nameEn: 'Plum', amount: '٢٠٠غ', amountEn: '200 g', calories: 115, glyph: '🟣' },
  { id: 'avocado', name: 'أفوكا', nameEn: 'Avocado', amount: '٧٠غ', amountEn: '70 g', calories: 115, glyph: '🥑' },
  { id: 'watermelon', name: 'بطيخ', nameEn: 'Watermelon', amount: '٤٠٠غ', amountEn: '400 g', calories: 115, glyph: '🍉' },
  { id: 'orange', name: 'ليمون', nameEn: 'Orange', amount: '٢٠٠غ', amountEn: '200 g', calories: 115, glyph: '🍊' },
  { id: 'persimmon', name: 'خرمة', nameEn: 'Persimmon', amount: '٢٠٠غ', amountEn: '200 g', calories: 115, glyph: '🟠' },
  { id: 'pear', name: 'إجاص', nameEn: 'Pear', amount: '٢٠٠غ', amountEn: '200 g', calories: 115, glyph: '🍐' },
  { id: 'grapes', name: 'عنب', nameEn: 'Grapes', amount: '١٥٠غ', amountEn: '150 g', calories: 115, glyph: '🍇' },
  { id: 'berries', name: 'فريز', nameEn: 'Strawberries', amount: '٤٠٠غ', amountEn: '400 g', calories: 115, glyph: '🍓' },
  { id: 'custard-apple', name: 'قشطة', nameEn: 'Custard apple', amount: 'حبة متوسطة', amountEn: '1 medium', calories: 115, glyph: '🍈' },
  { id: 'pomegranate', name: 'رمان', nameEn: 'Pomegranate', amount: 'حبة متوسطة', amountEn: '1 medium', calories: 115, glyph: '🔴' },
]

export const guidance = [
  'ابدأ أول وجبة بعد ساعتين من الاستيقاظ.',
  'اترك ساعتين على الأقل بين الوجبة والتمرين.',
  'اشرب كوباً من الماء عند الاستيقاظ وقبل كل وجبة.',
  'المكسرات النيئة مسموحة بحد أقصى ٣٠ غراماً يومياً.',
]

export const habitTasks: { id: HabitId; label: string; labelEn: string; glyph: string }[] = [
  { id: 'meal-1', label: 'الوجبة الأولى', labelEn: 'Meal one', glyph: '🍳' },
  { id: 'meal-2', label: 'الوجبة الثانية', labelEn: 'Meal two', glyph: '🥗' },
  { id: 'meal-3', label: 'الوجبة الثالثة', labelEn: 'Meal three', glyph: '🍗' },
  { id: 'meal-4', label: 'الوجبة الرابعة', labelEn: 'Meal four', glyph: '🍽️' },
  { id: 'fruit', label: 'الفواكه', labelEn: 'Fruit', glyph: '🍎' },
  { id: 'workout', label: 'التمرين', labelEn: 'Workout', glyph: '🏋️' },
]

export const sportOptions: { id: SportPreference; label: string; labelEn: string; glyph: string }[] = [
  { id: 'gym', label: 'النادي', labelEn: 'Gym', glyph: '🏋️' },
  { id: 'home', label: 'تمارين منزلية', labelEn: 'Home workout', glyph: '🏠' },
  { id: 'run', label: 'جري', labelEn: 'Running', glyph: '🏃' },
  { id: 'bike', label: 'دراجة', labelEn: 'Cycling', glyph: '🚴' },
  { id: 'swim', label: 'سباحة', labelEn: 'Swimming', glyph: '🏊' },
  { id: 'walk', label: 'مشي', labelEn: 'Walking', glyph: '🚶' },
  { id: 'yoga', label: 'يوغا', labelEn: 'Yoga', glyph: '🧘' },
  { id: 'football', label: 'كرة قدم', labelEn: 'Football', glyph: '⚽' },
]
